### ISSUE TITLE
Not possible to remove all tags

### ISSUE THREAD

**Issue by adrianrudnik** [Bee-Lab/BeelabTagBundle#1]
If I have an entity with at least one tag and I try to remove all tags (so it has no more tags), the change will not be persisted.

As a removal of all tags is registered as an update event as well (due to the updatedAt), the important part will be skipped because $tagNames will be NULL and skipped at:

```
    protected function setTags(TaggableInterface $entity, $update = false)
    {
        ...
        if (empty($tagNames)) {
            return;
        }
        ...
    }
```

This makes it impossible to remove all tags from an entity.

**Comment by ylegrand** [comment]
Good evening,

Do  you have an estimated delivery date for this patch ? I'm experiencing the exact same behaviour.

Thanks a lot.
