### ISSUE TITLE
Readme.md / documentation

### ISSUE THREAD

**Issue by antoine-nedelec** [Bee-Lab/BeelabTagBundle#10]
Hello, 

I am trying to use your library, but I couldn't manage to make it work until now, I created a [StackOverflow post](https://stackoverflow.com/questions/51827201/using-beelabtagbundle-library-on-symfony) but didn't received any help from it. 

I know this is not the right place as it is for issues, but I don't know where to ask anymore. Could you give me some more information about how to use your library ?

Thanks a lot.

**Comment by garak** [comment]
I'm not sure to understand your problem

**Comment by antoine-nedelec** [comment]
I can't manage to show in a twig template one of your Tag entity.

I do have my form builder under App\Form\Type\TagsTextType, with a simple buildform like this:

```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tagsText', TextType::class, ['required' => false, 'label' => 'Tags'])
        ;
    }
```
But I do not know how to generate the form in the end, I don't think i'm supposed to use [this way](https://symfony.com/doc/current/forms.html):

```
        $builder->create($entity)
            ->add('keywords', TextType::class, array(['required' => false, 'label' => 'Tags']))
            ->getForm();
```

And I tried the [Form Type Extension](https://symfony.com/doc/current/form/create_form_type_extension.html) also, and couldn't make it work either. Do you have any working example project that I could inspect to understand how to do it ? Or maybe the solution if it is really simple :)

**Comment by garak** [comment]
https://symfony.com/doc/current/forms.html#form-creating-form-classes

**Comment by garak** [comment]
Can we close this?

**Comment by antoine-nedelec** [comment]
Hello, yes sorry forgot to do that, but if I may i'l like to push 1 or 2 things in the documentation for the next novice person like me before you close it ?

**Comment by garak** [comment]
Feel free top open a pull request.
