### ISSUE TITLE
Error on install with SF4

### ISSUE THREAD

**Issue by thehatami** [Bee-Lab/BeelabTagBundle#11]
in a fresh install with composer, i get this msg. whats wrong?

`Compile Error: Declaration of App\Entity\Tag::setName($name) must be compatible with Beelab\TagBundle\Tag\TagInterface::setName(?string $name): void `

**Comment by garak** [comment]
New recipe should solve this issue. Of course, for already installed package you need to fix it manually (or remove and re-install package).
Thanks

**Comment by jknigga** [comment]
Just installed this package with composer and received the same error as above:

Compile Error: Declaration of App\Entity\Tag::setName(?string $name): void must be compatible with Beelab\TagBundle\Tag\TagInterface::setName($name)

This is a clean install.

**Comment by garak** [comment]
Try requiring `^2.1-dev `

**Comment by jknigga** [comment]
On which package?

**Comment by garak** [comment]
Never mind: I just released a new version. You can just upgrade

**Comment by jknigga** [comment]
Cool, that worked!
