### ISSUE TITLE
Update impossible SF4

### ISSUE THREAD

**Issue by ghost** [Bee-Lab/BeelabTagBundle#12]
Don't really know if this is an issue or not!?

Even if I implement the `update` variable in the `setTagsText` function, the update is triggered but the tags aren't updated? Looks like the entity isn't populated with the new values :(

Note : I've tried to extend the AbstractTaggable, same problem :/

Any idea on how to fix this issue ?

**Comment by garak** [comment]
You need to provide more info about your use case, otherwise any help is impossible

**Comment by ghost** [comment]
Well, I don't know what I could add. I've done the implementation following the documentation. My entity is called `PageRevision` instead of `Article` :) 
Here are the files, works better than words :)

[Files.zip](https://github.com/Bee-Lab/BeelabTagBundle/files/2415772/Files.zip)

**Comment by ghost** [comment]
I finally know that it's not a plugin issue ! Sorry for that post :(
It's probably due to the check done on update with getEntityChangeSet ... 

I've also moved to Selectize (instead of Select2). This plugin works straight out of the box on input element and can easily be implemented to use database ;)
