### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by thehatami** [Bee-Lab/BeelabTagBundle#13]
my entity show me this error:

`TagInterface $tag) must be compatible with Beelab\TagBundle\Tag\TaggableInterface::ad  
  dTag(Beelab\TagBundle\Tag\TagInterface $tag): void `

whats wrong?

**Comment by garak** [comment]
You need to add `:void` to your method's return type

**Comment by garak** [comment]
Docs are now updated and don't suggest wrong implementation.
