### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by butteredptarmigan** [Bee-Lab/BeelabTagBundle#22]
First, I would like to thank you all for the amazing bundle.

When installing the bundle in a Symfony 5 project with Flex, composer fails with this message:

```
$ composer require beelab/tag-bundle

Using version ^1.4 for beelab/tag-bundle
[...]
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beelab/tag-bundle v1.4.1 requires symfony/config ^3.4 || ^4.0 -> no matching package found.
    - beelab/tag-bundle v1.4.0 requires symfony/config ^3.4|^4.0 -> no matching package found.
    - Installation request for beelab/tag-bundle ^1.4 -> satisfiable by beelab/tag-bundle[v1.4.0, v1.4.1].
```

I suppose it is a matter of compatibility with Symfony 5. I would deeply appreciate an update introducing support for this version if that is the case.

**Comment by garak** [comment]
We already support Symfony 5, we only need a tag.
I'll try to release a new tag as soon as possible, meanwhile you can use our branch alias to get latest version (see composer.json)

**Comment by butteredptarmigan** [comment]
Thank you very much!
