### ISSUE TITLE
Field(s) 'tagsText' doesn't exist

### ISSUE THREAD

**Issue by bepabg** [Bee-Lab/BeelabTagBundle#23]
I'm trying to make tags in translations.
I use Symfony 5.0.7, Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface, Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait and A2lix\TranslationFormBundle\Form\Type\TranslationsType
If I set tags in not translatable entity everything is OK, but when I moved it to Translatable Entity, set to FormType
        $builder->add('translations', TranslationsType::class, array(
        'fields' => array(
            'title' => array('field_type' => TextType::class),
            'slug' => array('field_type' => TextType::class),
             'tagsText' => array('field_type' => TextType::class,  array('label' => 'Tags:'))));

I received error: Field(s) 'tagsText' doesn't exist in App\Entity\BlogTranslation

When I try to call in FormType only 
$builder->add('translations', TranslationsType::class);
at view there aren't any tag input field

Is it possible to make tags in translatable entity?

**Comment by garak** [comment]
That property is expected to be in the entity implementing `TaggableInterface`

**Comment by bepabg** [comment]
> TaggableInterface

class BlogTranslation implements TranslationInterface, TaggableInterface

**Comment by garak** [comment]
So, it looks like you missed to add property to such class

**Comment by bepabg** [comment]
That's my entity

```php
<?php

namespace App\Entity;


use Beelab\TagBundle\Tag\TaggableInterface;
use Beelab\TagBundle\Tag\TagInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogTranslationRepository")
 */
class BlogTranslation implements TranslationInterface, TaggableInterface
{

    use Common\IdTrait;
    use TranslationTrait;



    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;


    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255, nullable=true)
     */
    private $slug;


      /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     */
    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Tag")
     */
    private $tags;

    // note: if you generated code, you need to
    // replace "Tag" with "TagInterface" where appropriate

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function addTag(TagInterface $tag): void
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }
    }

    public function removeTag(TagInterface $tag): void
    {
        $this->tags->removeElement($tag);
    }

    public function hasTag(TagInterface $tag): bool
    {
        return $this->tags->contains($tag);
    }

    public function getTags(): iterable
    {
        return $this->tags;
    }

    public function getTagNames(): array
    {
        return empty($this->tagsText) ? [] : \array_map('trim', explode(',', $this->tagsText));
    }

    private $tagsText;

    /**
     * @var \DateTimeInterface
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

 
    public function setTagsText(?string $tagsText): void
    {
        $this->tagsText = $tagsText;
        $this->updated = new \DateTimeImmutable();
    }

    public function getTagsText(): ?string
    {
        $this->tagsText = \implode(', ', $this->tags->toArray());

        return $this->tagsText;
    }
}
```

**Comment by garak** [comment]
Well, it's clear that you changed such entity (or mess something else), since you can't get an error of non existent property that actually exists.

Can we start over?
Can you tell what is your current situation, what you do and what happens?

**Comment by bepabg** [comment]
Link for all files
https://github.com/bepabg/Blog

If you build it, create database and run localhost/blog/new you will see the error:

> Field(s) 'tagsText' doesn't exist in App\Entity\BlogTranslation

**Comment by garak** [comment]
I tried, and found that problem is in `TranslationsType` from TranslationFormBundle.
I guess that you should ask for support there.

**Comment by bepabg** [comment]
OK, thank you
