### ISSUE TITLE
Tagged Entity count

### ISSUE THREAD

**Issue by Filoz** [Bee-Lab/BeelabTagBundle#3]
Hi, 
I would like to store a count of how much a tag is used.
So I thought about the possibility do add a field to TagEntity to store that value. I also need to add a event listener that make the count query (on every add tag persist) and then update the count value in the Entity.

Do you think that it can works?
My only doubt are on the listener, because your Bundle listen for onflush event and I don't know if this can be a problem.

I want to store the count because I have to make a "tag cloud", something like this: http://mistic100.github.io/jQCloud/

Thanks for your work!

**Comment by garak** [comment]
Can't you just count the tags?

**Comment by Filoz** [comment]
Yes, but I think than i can be a performance issue doing every time a count in a large db.
Ok, I can cache the result, but I need the count in different situation and I can't always cache

**Comment by garak** [comment]
It looks like the impossibility of using a cache is an edge case, that cannot justify adding a superfluous information to the model
