### ISSUE TITLE
Error on partial load

### ISSUE THREAD

**Issue by alfons56** [Bee-Lab/BeelabTagBundle#6]
Hi,

I have an issue with saving a partialy selected entity, situation is as follows:

Data is retrieved partialy to avoid fetching excessive amounts of data. i am only interested in the 'something' and 'taggable' entities, not the tags themselves
```
    public function getSometing()
    {
        $query = $this
            ->createQueryBuilder('something')
            ->select('something, taggable')
            ->join('something.taggable', 'taggable')
            ...
            ->getQuery();
        $query->setHint(\Doctrine\ORM\Query::HINT_FORCE_PARTIAL_LOAD, 1);
        return $query->getResult();
    }
```
When editing and flushing the 'taggable' entity, symfony crashes with the following error:

..._logger.ERROR: Warning: Invalid argument supplied for foreach() ["[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /data/www/public_html/vendor/beelab/tag-bundle/Listener/TagSubscriber.php:124)"] []

In the setTags method the code assumes $oldTags is an array:
```
protected function setTags(TaggableInterface $entity, $update = false)
    {
        ...
        // if updating, need to check if some tags were removed
        if ($update) {
            foreach ($oldTags as $oldTag) {                                        //<- line 124
                if (!in_array($oldTag->getName(), $tagNames)) {
                    $entity->removeTag($oldTag);
                }
            }
        }
        ...
    }
```
Since the field has not been hydrated and also the constructor is not called, $oldTags is null in stead of an empty ArrayCollection, causing the flush to fail.

Can you have a look at this please?
Thanks!

**Comment by garak** [comment]
I'm afraid you're breaking the TaggableInterface, where `getTags()` must return an array or an ArrayCollection.
Also, I'm not sure that updating a partially hydrated entity could be considered a safe approach

**Comment by alfons56** [comment]
I see what you mean about partially hydrated entities, however, the taggable entity is fully hydrated, just not the relations it has.

Returning 'new ArrayCollection()' from getTags() will result in all existing tags being deleted so that is not a solution.

**Comment by garak** [comment]
No relations = not fully hydrated

**Comment by alfons56** [comment]
Ok, i see.
The TagSubscriber still crashes the request though, which is not expected behavior. just letting you know there is a problem. Solve it if you want.
I solved it by detaching the listener.

Thanks.
