### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by Icewild** [Bee-Lab/BeelabTagBundle#8]
Hi there. 
As i can see in your code you have added support for symfony4. But there is a problem, when i try to install your bundle, i get next error:
`"- beelab/tag-bundle v1.2.0 requires symfony/symfony ^2.8|^3.2 -> satisfiable by symfony/symfony"`

I checked tag in your repo, and i see that v1.2.0 tag points to source code from Jan 2017.
Can you update tag of your repo to current source code?

**Comment by garak** [comment]
Just released `v1.3.0`. Enjoy!
