### ISSUE TITLE
The child node "tag_class" at path "beelab_tag" must be configured.

### ISSUE THREAD

**Issue by valentin-harrang** [Bee-Lab/BeelabTagBundle#9]
Hi,

I'm using Symfony 4 and I have this error : 

> The child node "tag_class" at path "beelab_tag" must be configured.

It is written in your documentation that you have to configure the Bundle in app / config / config.yml but in Symfony 4 this file does not exist anymore

How can i configure it ?

Thanks in advance

**Comment by garak** [comment]
Any configuration file that is included in Symfony is fine

**Comment by valentin-harrang** [comment]
Why it does not work ?

**Comment by garak** [comment]
Sorry, I can't read your computer. Not yet

**Comment by garak** [comment]
Can we close this?
